### ISSUE TITLE
Cairo & GTK3

### ISSUE THREAD

**Issue by wdlkmpx** [emorozov/gtkballs#4]
These are some thoughs I have.

Currently the code only supports GTK2, and it will take some time to make a gtk3 port compile, and a long time to make a gtk4 port compile.

With gtk2, it's possible to move GdkDrawable stuff to cairo, so that migration to gtk3 becomes easy after that. 

But meanwhile the dialogs and windows can be adjusted to compile under gtk3 with a new configure param: `./configure --enable-gtk3`, and basically a broken app that compiles with gtk3 and stuff could be slowly fixed until it's fully working.

I have a special file, gtkcompat.h, which makes it easier to use many GTK3 functions while app still compiles with gtk2.

The sad part is that I've already made changes and I see they don't work as expected, so just replacing gdk_draw_* functions is not enough, a proper understanding of the old (gdk_draw_*) and the new (cairo_* gdk_pixbuf_*) functions is required.. and also concepts like layers, mask, alpha.. stuff I don't really understand right now.

I have the same problems porting Gdk stuff to Cairo in gWaveEdit and XEmeraldia, the apps work basically the same but visual glitches appear, it just requires advanced knowledge of deprecated and new functions and the interaction between cairo/gdk and gtk.

So what do you think?

**Comment by emorozov** [comment]
Sounds like a plan.

**Comment by wdlkmpx** [comment]
The gtk4 manual states that migration from gtk2 to gtk4 is not
documented, it has to be from gtk2 to gtk3, and from gtk3 to gtk4.

Gtk4 introduces too many changes, removes the gdk_cairo_*, so overall
I see this how it works:

By using the same codepaths and gtkcompat.h, small apps usually
compile with gtk2 and gtk3 with basically the same code and very few
lines for specific version stuff.

Gtk4 certainly breaks that model and many functions have to be
reimplemented, the guys introduced too many incompatible changes.

But forgetting about icons in buttons and menus makes things easier,
the Gnome guys hate button icons and menu icons and have deprecated many
related functions in gtk3, which are removed in gtk4.

The uglier and more primitive the app, the better for the Gnome guys,
the designers.

**Comment by wdlkmpx** [comment]
PR 12 adds gtk3 support. It works fine for me, all the dialogs look ok, the game works, it might need some minor tweaks.

The next step is gtk4 support, while keeping gtk3 support and maybe even gtk2 support, it's not impossible, avoiding #ifdefs as much as possible, but it's something that requires more entries in gtkcompat.h

something like:
`#define gtk_window_set_child(w,c) gtk_container_add(GTK_CONTAINER(w),c)`
